[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gam&+"
authors = [{name = "Graziella", email = "gamandplus@gmail.com"}]
dynamic = ["version", "description"]
